version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_CLIENT_PASSWORD}
      - xpack.security.enabled=true
      - logger.level=warn
    ports:
      - 9200:9200
  backend:
    build: .
    container_name: real_estate_backend
    ports:
      - 5001:5001
    restart: on-failure
    env_file:
      - .env  
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run server  
    depends_on:
      - elasticsearch